#!/usr/bin/env python

import os.path
from datetime import datetime
from functools import lru_cache

import click
import yaml
from cachetools import cached
from cachetools.keys import hashkey
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from pytz import timezone

# constants
CONFIG_PATH = f"{os.environ['HOME']}/.config/rofi-calendar"
CREDENTIALS_FILE = f"{CONFIG_PATH}/credentials.json"
SETTINGS_FILE = f"{CONFIG_PATH}/settings.yml"
TOKEN_FILE = f"{CONFIG_PATH}/token.json"

# If modifying these scopes, delete the file token.json.
SCOPES = ["https://www.googleapis.com/auth/calendar.readonly"]


@cached(cache={}, key=lambda **_: hashkey(None))
def settings(**overrides):
    """
    Read settings from settings.yml and allow init with overrides.
    Further calls are cached and will ignore the overrides argument.
    """
    with open(SETTINGS_FILE) as file:
        config = yaml.safe_load(file).get("settings", {})

    for k, v in overrides.items():
        if v is not None:
            config[k] = v

    return config


def credentials():
    """
    Get Google Credentials from the credentials.json file
    and stores a token.json for next calls.
    """
    creds = None

    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open(TOKEN_FILE, "w") as token:
            token.write(creds.to_json())

    return creds


def fetch_events(service, calendar_id, page_token=None):
    """
    Call Google Calendar API with calendar_id.
    Recursively calls itself if there is paginated results.
    """
    events_result = (
        service.events()
        .list(
            calendarId=calendar_id,
            timeMin=start_date(),
            timeMax=end_date(),
            singleEvents=True,
            orderBy="startTime",
            pageToken=page_token,
        )
        .execute()
    )

    # loop through response pages
    next_page = events_result.get("nextPageToken", None)
    if next_page:
        return events_result.get("items", []) + fetch_events(
            service, calendar_id, next_page
        )

    return events_result.get("items", [])


@lru_cache(maxsize=None)
def start_date():
    """
    Start date to look for events.
    """
    config = settings()

    tz_info = timezone(config["timezone"])
    date = (
        tz_info.localize(datetime.fromisoformat(config["start_date"]))
        if config.get("start_date", None)
        else datetime.now(tz_info)
    )

    return date.isoformat()


@lru_cache(maxsize=None)
def end_date():
    """
    End date to look for events.
    """
    config = settings()

    tz_info = timezone(config["timezone"])
    date = (
        tz_info.localize(datetime.fromisoformat(config["end_date"]))
        if config.get("end_date", None)
        else datetime.now(tz_info)
    )

    return date.isoformat()


def format_event_line(event):
    config = settings()
    tz_info = timezone(config["timezone"])

    event_start = datetime.fromisoformat(event["start"]["dateTime"])
    event_end = datetime.fromisoformat(event["end"]["dateTime"])
    event_summary = event["summary"]
    # event_description = event['description']

    now = datetime.now(tz_info).replace(
        hour=23, minute=59, second=59, microsecond=999999
    )
    difference = now - event_start
    if difference.days == 0:
        return f"Today      {event_start.strftime('%H:%M')} - {event_end.strftime('%H:%M')} {event_summary}"
    elif difference.days == -1:
        return f"Tomorrow   {event_start.strftime('%H:%M')} - {event_end.strftime('%H:%M')} {event_summary}"
    else:
        return f"{event_start.strftime('%Y-%m-%d %H:%M')} - {event_end.strftime('%H:%M')} {event_summary}"


@click.command()
@click.option(
    "-s",
    "--start",
    "--start-date",
    help="Start date to fetch events from (default to now).",
    default=datetime.now().isoformat(),
)
@click.option(
    "-e",
    "--end",
    "--end-date",
    help="End date to fetch events until (default to end of today).",
    default=datetime.now()
    .replace(hour=23, minute=59, second=59, microsecond=999999)
    .isoformat(),
)
def main(
    start: str,
    end: str,
):
    """
    Fetch calendar events and print in a format suitable for rofi.
    Used as: rofi -show cal -modes cal:rofi-calendar
    """
    # initialize config with overrides, if any
    config = settings(**{"start_date": start, "end_date": end})
    # initializer calendar service
    service = build("calendar", "v3", credentials=credentials())

    all_events = []

    for calendar_id in config["calendar_id"]:
        events = fetch_events(service, calendar_id)

        if not events:
            # no upcoming events for calendar
            continue

        for event in events:
            all_events.append(event)

    all_events.sort(
        key=lambda ev: ev["start"]["dateTime"]
        if "dateTime" in ev["start"]
        else ev["start"]["date"]
    )

    for ev in all_events:
        print(format_event_line(ev))


if __name__ == "__main__":
    main()
